cpp_file1 := main.cpp
output_file1 := famousRinconCastro1

cpp_file2 := rinconCastro2.cpp
output_file2 := famousRinconCastro2

famousRinconCastro1: $(cpp_file1)
	g++ -std=c++11 -g $(cpp_file1) -o $(output_file1)

famousRinconCastro2: $(cpp_file2)
	g++ -std=c++11 -g $(cpp_file2) -o $(output_file2)

clean:
	rm $(output_file)